#This workflow will run unit tests on the codebase and check for any errors and warnings.

name: Run Unit Tests for Polymathee SME Backend (Python)

on:
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 #v3 is the latest version of checkout

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        python -m pip install .[dev]
        if [ -f pyproject.toml ]; then pip install .; fi

    - name: Update Flake8
      run: python -m pip install --upgrade flake8

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Analysing the code with pylint
      run: |
        pylint polymathee_sme  --fail-under=${{ secrets.PYLINT_FAIL_UNDER }}